### ISSUE TITLE
Update contactview_metadata to adhere to Updated CHT-Core

### ISSUE THREAD

**Issue by yrimal** [medic/medic-couch2pg#61]
Current version of [contactview_metadata](https://github.com/medic/medic-couch2pg/blob/1bbab3e3014504eb1699f1e5317d6abf73b8bfb9/libs/analytics/migrations/201606200952.do.2318-prepareContacts.sql#L6-L9) was last updated on 2018. Since then, we've added configurable hierarchy to CHT-Core and for most of the partners using latest version of CHT-Core, `contact_type` field is also important. 

Whenever couch2pg runs, it creates contactview_metadata, so we should ensure that we're creating required field in contactview_metadata instead of partners/tech leads requiring to drop and recreate this mat view again.

**Comment by yrimal** [comment]
Hi @latin-panda ,
Current version of script doesn't reassign owner to full_access, hence that work needs to be taken care manually most of the time. 

Can you reassign the owner for each object after they're created to full_access as well? 
The syntax is :

```sql
ALTER [OBJECT_TYPE] [OBJECT_NAME] OWNER TO full_access;
```

**Comment by nomulex** [comment]
`full_access`  is a medic specific role, I am not sure if this is wise to  put it in the code that will be used by the cht community.

**Comment by yrimal** [comment]
I also thought about that. But, this repo (medic-couch2pg) is medic specific instance and I think we should put that. But not put REASSIGN on our public [repo](https://github.com/medic/couch2pg).

**Comment by latin-panda** [comment]
Hey guys, [I've verified](https://github.com/medic/medic-couch2pg/pull/64#issuecomment-787509423) and effectively this repo is designed to support all CHT deployments, even self hosted. So we should not hardcode Medic-specific roles, but we can include this as a separate script that runs in demand, I've raised [a ticket]( https://github.com/medic/medic-couch2pg/issues/66) to address this next.

**Comment by newtewt** [comment]
I've tested this in my local setup. By tearing down the current `medic-couch2pg` container and then spinning up one from this branch. The materialized view sql statement is updated in the properties and the query returns the screenshot below.  I am not sure how our Prod upgrade process works for `medic-couch2pg` and if it's worth verifying during this to ensure it doesn't break.

**Comment by newtewt** [comment]
![Screenshot from 2021-03-08 11-29-27](https://user-images.githubusercontent.com/10531066/110350764-0b220180-8002-11eb-89a4-05b6d3cc0b5a.png)

**Comment by newtewt** [comment]
@latin-panda  this is ready to merge.

**Comment by latin-panda** [comment]
[PR](https://github.com/medic/medic-couch2pg/pull/64) has been merged.
