### ISSUE TITLE
Update telemetry views to support daily aggregation

### ISSUE THREAD

**Issue by mrsarm** [medic/medic-couch2pg#85]
We have a PG view [useview_telemetry](https://github.com/medic/medic-couch2pg/blob/master/libs/medic-users-meta/migrations/202102191153.do.54-create-couchdb-users-meta-table.sql#L20-L31) with the telemetry data, and there is a field `period_start` that we need to adapt to the changes in medic/cht-core#6915, changes that will be released in the upcoming version of the CHT (v3.12.0).

**Comment by dianabarsan** [comment]
@mrsarm this is also resolved by https://github.com/medic/medic-couch2pg/pull/91, correct?

**Comment by mrsarm** [comment]
> @mrsarm this is also resolved by #91, correct?

Right, I added a reference in the PR to this ticket, thanks.

**Comment by mrsarm** [comment]
Ready for AT, along with the issues #86 and #87, branch `86-87-fix-meta-views`.

The description of the changes are described in the PR description: https://github.com/medic/medic-couch2pg/pull/91

More on what to test: https://github.com/medic/medic-couch2pg/issues/86#issuecomment-844394087

**Comment by newtewt** [comment]
Confirmed that postgress supports syncing of 3.11 and less versions of telemetry and manually created telemetry docs that match the 3.12 version and they sync as well. Dates and users are correct on both.
