### ISSUE TITLE
Unique index in `useview_telemetry` view by `period_start` and `user_name` cause migration to crash if a user has more than one device

### ISSUE THREAD

**Issue by mrsarm** [medic/medic-couch2pg#86]
The constraint `idx_useview_telemetry_period_start_user` defined [here](https://github.com/medic/medic-couch2pg/blob/5fd77a8d3eb8c5b237958bce285e4bcafffd96b5/libs/medic-users-meta/migrations/202102191153.do.54-create-couchdb-users-meta-table.sql#L43) makes each record in the `useview_telemetry` view unique by the columns `period_start` and `user_name`:

```sql
CREATE UNIQUE INDEX idx_useview_telemetry_period_start_user ON useview_telemetry(period_start,user_name);
```

But if a user has more than one devices it will send as many records with the same pair `(period_start,user_name)` as devices each month, this includes users that uses desktop browsers not just one mobile phone, so eg. a supervisor that access the CHT from 2 different computers with the same account will produce 2 records that will be stored in the `medic-users-meta` DB in Couch, then when synchronized with medic-couch2pg the records will collide, raising the following exception that will prevent this app to migrate the data from Couch to Postgres:

```diff
-[2021-05-14T20:33:45.835Z ERROR]:  error: duplicate key value violates unique constraint "idx_useview_telemetry_period_start_user"
    at Connection.parseE (/projects/medic/medic-couch2pg/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/projects/medic/medic-couch2pg/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/projects/medic/medic-couch2pg/node_modules/pg/lib/connection.js:113:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 551,
  severity: 'ERROR',
  code: '23505',
+  detail: 'Key (period_start, user_name)=(2021-05-01, adama) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'SQL statement "INSERT INTO public.useview_telemetry SELECT (diff.newdata).* FROM pg_temp_2.pg_temp_16536_2 diff WHERE tid IS NULL"\n' +
    'SQL statement "REFRESH MATERIALIZED VIEW CONCURRENTLY useview_telemetry"\n' +
    'PL/pgSQL function refresh_matviews() line 15 at EXECUTE statement',
  schema: 'public',
  table: 'useview_telemetry',
  column: undefined,
  dataType: undefined,
  constraint: 'idx_useview_telemetry_period_start_user',
  file: 'nbtinsert.c',
  line: '414',
  routine: '_bt_check_unique'
}
[2021-05-14T20:33:45.836Z ERROR]:  An unrecoverable error occurred
[2021-05-14T20:33:45.836Z ERROR]:  TypeError: Assignment to constant variable.
    at Object.run (/projects/medic/medic-couch2pg/libs/medic/runner.js:55:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-05-14T20:33:45.836Z ERROR]:  exiting
```

Even if it's unlikely this to happen, only bast with 1 user accessing from more than one device to make the whole process to fail.

I think the best solution is to patch the app removing the index, because even adding to the index something like the device id, the error is still likely to happen soon or later, because there are cases where a device can yield more than 1 aggregation with the same device within the same period.

If it's useful to query this data by user, we can change the index removing the unique constraint.

The solution should also take into account https://github.com/medic/medic-couch2pg/issues/85.

**Comment by dianabarsan** [comment]
The same issue is affecting another unique index: idx_useview_feedback_period_start_user. 

```
duplicate key value violates unique constraint "idx_useview_feedback_period_start_user"
```

I think we should indeed remove the unique constraint.

**Comment by newtewt** [comment]
@mrsarm I've completed testing on this. I think it is ready to merge.  As an additional test to what is documented below. I went from 3.1.0 to 3.2.0 and crashed. Then applied your branch and it started up and confirmed the new and old style telemetry docs sync.   Upgrading for me was to use docker-compose and change the image.


> Against a new PG database that wasn’t synchronized before, with any version of the CHT

 Started up a fresh instance on 3.9, upgrade to 3.11. Syncing occurred no issues. 
Seeded the test seed data.
Data synced 
Telemetry and meta data syncing from 2 different browsers with no crash. 

> Against a PG with data from CHT < 3.8.0 that has data previously synchronized with medic-couch2pg < 2.3.0

Used 3.7 cht-core, sent the data through to postgres via medic-couch2pg v3.1.0. Upgraded the medic-couch2pg instance to the branch version. The migrations ran and syncing is still happening. 

Updated to cht-core master, synced to pg the telemetry docs from chrome and firefox with same user.  No crashes and data shows. 

> Against a PG with data from CHT >= 3.8.0 that has data previously synchronized with medic-couch2pg < 3.2.0

Spun up 3.9 cht-core, with  medic-couch2pg 3.1.0. Seeded data. Updated to 3.11.0. Created some new docs under 3.11 and sync. Update to branch medic-couch2pg, migrations applied. Sync still working.

Any other combination that is possible to test.
On each test we should ensure that:

The process is not aborted for any reason and the data is migrated.

> To test the new format of telemetry we can instead of deploying the branch with the changes, just edit some existent records in the medic-users-meta DB. Normally a telemetry record has in the "metadata" section a field "year" and "month", now a new field "day" with the day of the month is added (number, 1-indexed). Also the id of the record contain the day month embedded, but that shouldn’t change the synchronization. Eg. a normal record id is telemetry-2021-5-greg-5517a586-d839-47cf-ae2c-8ca81ac9014b , now a daily telemetry record would have an id like telemetry-2021-5-19-greg-5517a586-d839-47cf-ae2c-8ca81ac9014b.

Created new telem docs post upgrade
Created new style telem docs pre-upgrade and migrated.* the records aren't migrated pre-3.2.0.  

> Another test to perform is check that 2 records with the same user_name and period_start won’t cause the indexes of the views to blow up the process, in both telemetry and feedback views. Accessing with the same user in 2 different devices will generate telemetry records with that collision, and the new version of medic-couch2pg tested should allow that because it removes the unique constraint in the view. Another way would be duplicate some records from the medic-users-meta DB and then synchronize.

Created records pre and post upgrade of medic-couch2pg with duplicate users and dates. No crash.


> Telemetry records in the telemetry view should have the right month in the period_start column.

The period start works correctly for both versions. 

> The day in the same column also need to have the right number: 1 for monthly telemetry records, the same day that the field metadata.day has in the CouchDB record.
The dates match what is set on the doc in the column.
