### ISSUE TITLE
`useview_telemetry` is failing for instances running on CHT-Core > 3.8.0

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-couch2pg#87]
Reported error: 
```
[2021-05-17T08:32:50.708Z ERROR]:  { error: date/time field value out of range: "2020-13-1"
    at Connection.parseE (/var/adapter/shared/medic-couch2pg-v3.2.1/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/var/adapter/shared/medic-couch2pg-v3.2.1/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/var/adapter/shared/medic-couch2pg-v3.2.1/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:598:20)
  name: 'error',
  length: 294,
  severity: 'ERROR',
  code: '22008',
  detail: undefined,
  hint: 'Perhaps you need a different "datestyle" setting.',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'SQL statement "REFRESH MATERIALIZED VIEW CONCURRENTLY useview_telemetry"\nPL/pgSQL function refresh_matviews() line 15 at EXECUTE',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'datetime.c',
  line: '3890',
  routine: 'DateTimeParseError' }
```

It seems like this is related to this migration: 
https://github.com/medic/medic-couch2pg/blob/master/libs/medic-users-meta/migrations/202102191153.do.54-create-couchdb-users-meta-table.sql#L27

Where, instead of adding +1 when the instance version is lower than 3.8.0, we end up adding +1 when the instance is equal or greater, ending up with 13th month dates.

**Comment by mrsarm** [comment]
Assigning myself because I'll work today in the solution for #86 that affects the same view, and doing separate PRs from each one would imply 2 different migrations scripts, recreating 2 times the same view, because PG does not allow to alter views to just change column definitions.

**Comment by mrsarm** [comment]
Ready for AT, along with the issues #86 and #87, branch `86-87-fix-meta-views`.

The description of the changes are described in the PR description: https://github.com/medic/medic-couch2pg/pull/91

More on what to test: https://github.com/medic/medic-couch2pg/issues/86#issuecomment-844394087

**Comment by mrsarm** [comment]
Ready for AT, along with the issues #85 and #86, branch `86-87-fix-meta-views`.

The description of the changes are described in the PR description: https://github.com/medic/medic-couch2pg/pull/91

More on what to test: https://github.com/medic/medic-couch2pg/issues/86#issuecomment-844394087

**Comment by newtewt** [comment]
confirmed that versions 3.11.0 and 3.7.0 creating telemetry and thing syncing to postgress are not failing and have the proper month set.
